spring.application.name=dailymotionminer

server.port=8081
dailymotion.baseuri=https://api.dailymotion.com/

dailymotion.maxVideos=10
dailymotion.maxPages=2

videominer.uri=http://localhost:8080/api/videominer/channels